sudo: false
language: java
jdk:
  - openjdk7

sudo: false

notifications:
  email: false

addons:
  apt:
    packages:
      - protobuf-compiler

cache:
  directories:
    - $HOME/.m2

before_script:
  - mavenize_file_layout.sh